### ISSUE TITLE
Not a valid Win32 Application

### ISSUE THREAD

**Issue by cunev** [iberatkaya/mousebot#4]
```
C:\Users\Dmitriy SSD\Desktop\RuntimeV2>node index
internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Dmitriy SSD\Desktop\RuntimeV2\node_modules\mousebot\native\index.node is not a valid Win32 application.
\\?\C:\Users\Dmitriy SSD\Desktop\RuntimeV2\node_modules\mousebot\native\index.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Dmitriy SSD\Desktop\RuntimeV2\node_modules\mousebot\lib\index.js:47:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

Tried all versions of Node from 10 to 14.

**Comment by cunev** [comment]
when you make modules, you are supposed to maintain them.
